application: ihsmamdi03app2010
version: 1
runtime: python
api_version: 1

handlers:
- url: /groups.*
  script: groups/controller.py  
- url: /msg.*
  script: msg/controller.py
- url: /mensa
  script: mensa/controller.py
- url: /stupla.*
  script: stupla/main.py
- url: /.*
  script: helloworld.py
